Project Review
clin2on3mun/Review-Project-Trials pull request #1
Opened 2023-03-27 08:14 UTC by clin2on3mun

portfolio project: a project built with HTML and CSS 

- it is a mobile version of the portfolio
-it uses HTML semantics tags and CSS layouts.

2023-03-27 08:34 UTC, clin2on3mun commented
Hi  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
<img src="https://www.animatedimages.org/data/media/1103/animated-congratulation-image-0056.gif"/>

## Highlights
- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️
- 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 08:46 UTC, OyePriscilla requested changes
Hi @clin2on3mun 👏 👏 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Good use of summary template ✔️ 

## Required Changes ♻️

- [ ] **Please as stated in the requirement, kindly ensure to use the** [GitHub inline comments feature](https://docs.github.com/en/github/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request) **to add at least 2 to review comments.**

<img width="752" alt="Untitled" src="https://user-images.githubusercontent.com/103386183/227890359-16b19f61-715d-46a8-a5d4-83ee3a71c7be.png">


Make sure the student left the comment under a line or block of code that fits the context the comment is about. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 09:23 UTC, clin2on3mun reviewed
Hi @clin2on3mun , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![soclose](https://user-images.githubusercontent.com/97100091/199273222-010c4c63-4b9f-4149-9cac-ca9dde88e551.gif)

## Highlights
✅ Good GitHub Flow
✅ Great design 👏 
✅ No Linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 09:23 UTC, clin2on3mun commented on index.html
> +                    </div>
i would suggest you use the HTML semantics tag (eg: section) where you use div you can read about<a href="https://www.pluralsight.com/guides/semantic-html">HTML semantics</a> to get an idea on changes and why you will make them

2023-03-27 09:23 UTC, clin2on3mun commented on index.html
> +                    <span class="nav-bar"></span>
I would suggest you always close HTML Tags because it show that is closing tag and end of that element

2023-03-27 09:41 UTC, NahnahAJ commented
## Project Status: APPROVED :green_circle: 
Hi @clin2on3mun, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
- Inline comments added :100: 

## Optional suggestions
- Great job adding inline comments as mentioned by the previous reviewer :+1:. I will suggest that you include emojis in your reviews so it sends a friendly tone to the recipient. Also, I will suggest that you make sure your sentences are well phrased so the student understands what is expected of them and is able to deliver :100: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-27 10:03 UTC, merged

2023-03-28 07:26 UTC, uno36 commented on index.html
> +            </div>
Great Job on the work so far you have put much effort, 👦

- I suggest using a list for your links this makes it easier for you to target them in your html for example
~~~~
 <ul>
          <li> link1 <li>
          <li> link2 <li>
           <li> link3 <li>
            <li> link4 <li>
 <ul>
~~~~